<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Glide.js CSS -->
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@glidejs/glide@3.5.2/dist/css/glide.core.min.css">
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@glidejs/glide@3.5.2/dist/css/glide.theme.min.css">
  <style>
    .glide {
      width: 100%;
      max-width: 1200px; /* Optional limit for large screens */
      margin: 0 auto;
      position: relative;
    }

    .glide__slide {
      display: flex;
      justify-content: center;
      align-items: center; /* Vertically center the images */
      position: relative; /* Enable layering */
    }

    .glide__slide img {
      transition: transform 0.3s ease, opacity 0.3s ease, z-index 0.3s ease;
      border-radius: 10px;
    }

    /* Main image styling */
    .glide__slide--active img {
      width: 140%; /* Make the main image larger */
      transform: scale(1.8); /* Enlarge the main image */
      z-index: 2; /* Bring the main image to the front */
      opacity: 1;
      box-shadow: 0px 25px 50px rgba(0, 0, 0, 0.4); /* Add shadow for depth */
      margin-left: -25%; /* Overlap left preview */
      margin-right: -25%; /* Overlap right preview */
    }

    /* Preview image styling */
    .glide__slide:not(.glide__slide--active) img {
      width: 110%; /* Smaller size for preview images */
      transform: scale(0.8); /* Scale down preview images */
      z-index: 1; /* Push preview images to the back */
      opacity: 0.5; /* Reduce opacity for preview images */
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="glide">
      <div class="glide__track" data-glide-el="track">
        <ul class="glide__slides d-flex align-items-center justify-content-center" id="carousel-slides">
          <!-- Slides will be dynamically injected here -->
        </ul>
      </div>
      <!-- Navigation -->
      <div class="glide__arrows" data-glide-el="controls">
        <button class="glide__arrow glide__arrow--left" data-glide-dir="<">‹</button>
        <button class="glide__arrow glide__arrow--right" data-glide-dir=">">›</button>
      </div>
      <div class="glide__bullets" data-glide-el="controls[nav]">
        <!-- Bullets will be auto-generated by Glide.js -->
      </div>
    </div>
  </div>

  <!-- Glide.js JS -->
  <script src="https://cdn.jsdelivr.net/npm/@glidejs/glide@3.5.2/dist/glide.min.js"></script>
  <script>
    // Path to images
    const imagePath = 'public/img/top-agents/';
    const imageNames = ['image1.png', 'image2.png', 'image3.png'];

    // Dynamically generate carousel slides
    const carouselSlides = document.getElementById('carousel-slides');
    imageNames.forEach((imageName, index) => {
      const li = document.createElement('li');
      li.classList.add('glide__slide');
      li.innerHTML = `<img src="${imagePath}${imageName}" alt="Slide ${index + 1}">`;
      carouselSlides.appendChild(li);
    });

    // Initialize Glide.js with settings for previews
    new Glide('.glide', {
      type: 'carousel',
      startAt: 1, // Start at the second image
      perView: 3, // Show 3 images (main + previews)
      focusAt: 'center', // Focus on the center image
      gap: 10, // Small gap for tighter layout
      autoplay: 3000, // Auto-scroll every 3 seconds
      animationDuration: 800,
      animationTimingFunc: 'ease-in-out',
      hoverpause: true // Pause on hover
    }).mount();
  </script>
</body>
</html>
